# Memory components add-on for conversation persistence and speaker identification
services:
  orchestrator:
    build: ./orchestrator
    environment:
      - MEMORY_ENABLED=true
      - DIGLETT_URL=http://diglett:80
      - CHROMADB_URL=http://chromadb:8002
      - REDIS_URL=redis://redis:6379
    depends_on:
      diglett:
        condition: service_started
      chromadb:
        condition: service_healthy
      redis:
        condition: service_started

  diglett:
    build:
      context: ./diglett
      dockerfile: Dockerfile
    ports:
      - "3210:80"
    volumes:
      - diglett-data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes --maxmemory 1gb --maxmemory-policy allkeys-lru
    restart: unless-stopped

  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8002:8000"
    volumes:
      - ./data/chromadb:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - ANONYMIZED_TELEMETRY=FALSE
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 10s
      timeout: 10s
      retries: 15
    restart: unless-stopped

volumes:
  diglett-data:
