include:
  - docker-compose.speaker.yml

services:
  orchestrator:
    build:
      context: ./orchestrator
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - WHISPER_URL=${WHISPER_URL:-http://whisper-live:9090}
      - OLLAMA_URL=${OLLAMA_URL:-http://host.docker.internal:11434}
      - TTS_URL=${TTS_URL:-http://kokoro:8880}
      - MEMORY_ENABLED=${MEMORY_ENABLED:-false}
      - AMEM_URL=${AMEM_URL:-http://a-mem:8001}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - LLM_MODEL=${LLM_MODEL:-gemma3n:latest}
      - TTS_VOICE=${TTS_VOICE:-af_bella}
    depends_on:
      - whisper-live
      - kokoro
    restart: unless-stopped

  whisper-live:
    build:
      context: https://github.com/collabora/WhisperLive.git
      dockerfile: docker/Dockerfile.gpu
    ports:
      - "9090:9090"
    volumes:
      - ./data/models/whisper:/models
    environment:
      - MODEL_SIZE=${STT_MODEL:-tiny}
      - VAD_ENABLED=true
      - CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-0}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped

  kokoro:
    image: ghcr.io/remsky/kokoro-fastapi-gpu:v0.2.1
    ports:
      - "8880:8880"
    environment:
      - DEFAULT_VOICE=${TTS_VOICE:-af_bella}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped

  voice-ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NEXT_PUBLIC_WS_URL=${WS_URL:-ws://localhost:8000/ws}
      - ORCHESTRATOR_URL=${ORCHESTRATOR_URL:-http://orchestrator:8000}
      - NEXT_PUBLIC_WHISPER_WS_URL=${WHISPER_WS_URL:-ws://localhost:9090}
    depends_on:
      - orchestrator
    restart: unless-stopped

networks:
  default:
    name: voice-net